name: kinkan_calc
description: لعبة حاسبة كنكنة
publish_to: none
version: 1.1.14+15

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  uuid: ^4.3.3   # ← لتوليد مُعرّف كل لعبة
  fl_chart: ^0.68.0       # ← للرسوم البيانية في الإحصائيات
  share_plus: ^9.0.0      # ← لمشاركة نتائج الألعاب
  file_picker: ^8.0.7     # ← لاستيراد ملفات البيانات

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
